data:extend(
{
    {
        type = "bool-setting",
        name = "spice-rack-longrange-turret",
        order = "a",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-change-military-research",
        order = "b",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-change-robot-follower-count",
        order = "c",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-flamethrower-debuff",
        order = "d",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-laser-drain",
        order = "e",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-more-grenade-base-damage",
        order = "f",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-change-landmine-cost",
        order = "g",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
})
