data:extend(
{
    {
        type = "bool-setting",
        name = "spice-rack-longrange-turret",
        order = "a",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-change-military-research",
        order = "b",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-change-robot-follower-count",
        order = "c",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-flamethrower-change",
        order = "d",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-laser-change",
        order = "e",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    -- {
    --     type = "bool-setting",
    --     name = "spice-rack-grenade-change",
    --     order = "f",
    --     setting_type = "startup",
    --     default_value = true,
    --     per_user = false,
    -- },
    {
        type = "bool-setting",
        name = "spice-rack-landmine-change",
        order = "g",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-spawner-change",
        order = "h",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-tank-change",
        order = "i",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-car-change",
        order = "j",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-repair-change",
        order = "k",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-shotgun-change",
        order = "k",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },

    
})
