data:extend(
{
    {
        type = "bool-setting",
        name = "spice-rack-longrange-turret",
        order = "a",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-change-military3-research",
        order = "b",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-change-military-research",
        order = "c",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-shotgun-change",
        order = "d",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-change-follower-robot-count",
        order = "e",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-flamethrower-change",
        order = "f",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-laser-change",
        order = "g",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-landmine-change",
        order = "h",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-spawner-change",
        order = "i",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-tank-change",
        order = "j",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-car-change",
        order = "k",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
    {
        type = "bool-setting",
        name = "spice-rack-repair-pack-change",
        order = "l",
        setting_type = "startup",
        default_value = true,
        per_user = false,
    },
})
